// Copyright 2026, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  Leia CNSDK display processor (Android), atlas-mode variant.
 *
 * Wraps leia_cnsdk as an xrt_display_processor. Uses CNSDK's atlas mode:
 * the compositor's pre-composited SBS atlas VkImage+View is passed
 * directly to CNSDK each frame via
 * leia_interlacer_vulkan_set_interlace_view_texture_atlas, and CNSDK
 * splits L/R internally. No per-view image management, no per-tile
 * blit, no blit cmd buffer / semaphore / fence on our side.
 *
 * Display metrics + face-tracked eye positions come from CNSDK once the
 * async core init completes (lazy on first query). Falls back to
 * hardcoded Lume Pad 2 metrics and IPD-only eyes while the core is
 * still booting.
 *
 * @author David Fattal
 * @ingroup drv_leia
 */

#include "leia_display_processor_cnsdk.h"
#include "leia_cnsdk.h"

#include "xrt/xrt_display_metrics.h"
#include "xrt/xrt_display_processor_vk.h" // #568 — VK/Android DP variant + set_transparent_background slot
#include "vk/vk_helpers.h"
#include "util/u_logging.h"

// #568 — post-weave alpha-gate SPIR-V (generated by spirv_shaders into the
// build dir; see drv_leia_android/CMakeLists.txt). Ported from the desktop DP.
#include "shaders/fullscreen_tri.vert.h"
#include "shaders/alpha_gate.frag.h"

#include <stdlib.h>

#ifdef XRT_OS_ANDROID
#include <sys/system_properties.h> // debug.dxr.alphagate A/B knob (#568)
#endif

#if defined(XRT_OS_ANDROID) && defined(XRT_DEBUG_ANDROID_VERBOSE)
#include <android/trace.h>
#endif


// Hardware-bring-up debug logging. Gated by XRT_DEBUG_ANDROID_VERBOSE
// (cppFlag from the Android Debug variant). Compiles to nothing in
// release. Tag "HW_DBG_DP:" greppable in logcat, separate from the
// CNSDK wrapper's HW_DBG_CNSDK tag.
#ifdef XRT_DEBUG_ANDROID_VERBOSE
#define DXR_HW_DBG(...)       U_LOG_I("HW_DBG_DP: " __VA_ARGS__)
#define DXR_HW_DBG_ONCE(...)  do {                                                                 \
		static bool _logged = false;                                                                \
		if (!_logged) { U_LOG_I("HW_DBG_DP[once]: " __VA_ARGS__); _logged = true; }                 \
	} while (0)
struct AtraceScopeDp {
	AtraceScopeDp(const char *name) { ATrace_beginSection(name); }
	~AtraceScopeDp() { ATrace_endSection(); }
};
#define DXR_ATRACE(name) AtraceScopeDp _atrace_##__LINE__(name)
#else
#define DXR_HW_DBG(...)       ((void)0)
#define DXR_HW_DBG_ONCE(...)  ((void)0)
#define DXR_ATRACE(name)      ((void)0)
#endif


namespace {

// Lume Pad 2-class defaults. Used until CNSDK reports the real device
// metrics through leia_core via the leia_cnsdk wrapper's cached values.
constexpr float kDefaultDisplayWidthM  = 0.1934f;  // ~12.4" diagonal, 16:10
constexpr float kDefaultDisplayHeightM = 0.1209f;
constexpr uint32_t kDefaultDisplayPixelW = 2560;
constexpr uint32_t kDefaultDisplayPixelH = 1600;

// Hardcoded IPD-only eye positions. Origin = display center; z is
// toward the user. 65 mm IPD, ~50 cm viewing distance.
constexpr float kIpdHalfM       = 0.0325f;
constexpr float kEyeViewerDistM = 0.5f;

struct leia_dp_cnsdk
{
	// #568: the VK/Android DP variant (embeds the generic base at offset 0 and
	// appends set_transparent_background). The factory advertises the variant
	// by setting dp_vk.base.struct_size = sizeof(struct xrt_display_processor_vk)
	// so the runtime discovers the appended slot (ADR-020 struct_size gate). The
	// embedded base is still at offset 0, so as_impl()'s reinterpret_cast holds.
	struct xrt_display_processor_vk dp_vk;
	struct leia_cnsdk *cnsdk;          //!< Owned.
	struct vk_bundle *vk;              //!< Borrowed from compositor.
	VkCommandPool cmd_pool;            //!< Borrowed from compositor; used by mono passthrough.

	// CNSDK's self-submitting Vulkan weave (leia_interlacer_vulkan_do_post_process)
	// needs a *caller-supplied* destination framebuffer (color + depth)
	// compatible with its internal interlace render pass. The runtime
	// compositor stays CNSDK-agnostic (ADR-019) and has no depth image, so
	// we build + own these here. The render pass + depth target are created
	// once per (w, h, color format); the per-swapchain-image color view +
	// framebuffer are cached because the compositor rotates target_image
	// through a small set of swapchain images.
	VkRenderPass weave_rp;
	VkImage weave_depth_img;
	VkDeviceMemory weave_depth_mem;
	VkImageView weave_depth_view;
	uint32_t weave_w;
	uint32_t weave_h;
	VkFormat weave_color_fmt;
	// The compositor's color view for the target image of the upcoming
	// process_atlas, handed to us via set_target_color_view. We do NOT own
	// it (the compositor created it and destroys it on swapchain resize) —
	// we only build framebuffers from it. Reusing it avoids creating our own
	// VkImageView on swapchain images, which Adreno faults on.
	VkImageView pending_target_view;
	// Framebuffer cache keyed by the compositor's color view. Each swapchain
	// image has one stable view, so this is bounded by the swapchain size.
	struct {
		VkImageView view;   //!< Borrowed key (compositor-owned).
		VkFramebuffer fb;   //!< Owned.
	} weave_fb_cache[8];
	uint32_t weave_fb_count;

	// --- Transparent-background alpha-gate (#568) ------------------------
	// The CNSDK weave destroys per-pixel alpha (it interlaces into opaque
	// RGB), so transparency is RECONSTRUCTED post-weave: a fullscreen pass
	// samples the original premultiplied atlas and writes (0,0,0,0) wherever
	// every view tile is α==0 — SurfaceFlinger then shows the live screen
	// through those holes (the Android in-process model, ADR-025). Ported
	// from the desktop DP's alpha_gate (src/drv_leia/leia_display_processor.cpp).
	bool transparent_bg_enabled;       //!< Set via set_transparent_background.
	bool client_present_mode;          //!< Always true on Android (SurfaceFlinger presents).
	bool ag_inited;                    //!< Pipeline/resources built (lazy, first gated frame).
	VkFormat ag_fmt;                   //!< Target format the pipeline/render pass were built for.
	VkSampler ag_sampler;              //!< Linear/clamp.
	VkDescriptorSetLayout ag_desc_layout;
	VkPipelineLayout ag_pipeline_layout;
	VkDescriptorPool ag_desc_pool;
	VkDescriptorSet ag_set;
	VkRenderPass ag_rp;                //!< Single color attachment; finalLayout = COLOR_ATTACHMENT_OPTIMAL.
	VkPipeline ag_pipeline;            //!< blendEnable=FALSE, colorWriteMask=RGBA (the footgun).
	// Intermediate copy of the woven target, sampled as the "backbuffer"
	// (binding 0) — you can't sample and render to the same image.
	VkImage ag_strip_img;
	VkDeviceMemory ag_strip_mem;
	VkImageView ag_strip_view;
	uint32_t ag_strip_w, ag_strip_h;
	// Output framebuffer cache keyed by the compositor's color view (reuse
	// pending_target_view — never mint our own swapchain-image view; Adreno
	// faults on that, same rationale as weave_fb_cache). Also keyed on (w,h):
	// on a portrait⇄landscape rotation the swapchain recreates and the driver
	// can RECYCLE a destroyed view handle for the new orientation, so a
	// view-only match could hand back a framebuffer built at the OLD dims —
	// rendering a 2560x1600 pass into a 1600x2560 framebuffer shears the image
	// (the landscape #568 bug). Matching on dims too forces a rebuild.
	struct {
		VkImageView view;   //!< Borrowed key (compositor-owned).
		VkFramebuffer fb;   //!< Owned.
		uint32_t w, h;      //!< Dims this fb was built for (rotation guard).
	} ag_fb_cache[8];
	uint32_t ag_fb_count;
};

inline leia_dp_cnsdk *
as_impl(struct xrt_display_processor *xdp)
{
	return reinterpret_cast<leia_dp_cnsdk *>(xdp);
}

// Mono / 2D-mode passthrough: blit the single-tile atlas directly to
// the swapchain target. No CNSDK weave (would be wrong for 1x1). Same
// barrier dance as the atlas-side host-stall path — drain via
// vkQueueWaitIdle so xrEndFrame sees the target image ready.
bool
mono_passthrough_blit(leia_dp_cnsdk *impl,
                      VkImage atlas_image,
                      uint32_t atlas_width,
                      uint32_t atlas_height,
                      VkImage target_image,
                      uint32_t target_width,
                      uint32_t target_height)
{
	DXR_ATRACE("dxr_dp:mono_passthrough_blit");
	struct vk_bundle *vk = impl->vk;
	if (vk == nullptr || vk->main_queue == nullptr) {
		// Defensive: this mono 1x1 fallback submits on the main queue
		// directly. The atlas-weave path guards vk==nullptr already;
		// mirror it here so a partially-initialized bundle can't deref
		// vk->main_queue->queue below.
		U_LOG_W("mono_passthrough_blit: vk bundle/main_queue not ready, skipping");
		return false;
	}

	VkCommandBufferAllocateInfo ai = {};
	ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	ai.commandPool = impl->cmd_pool;
	ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	ai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vk->vkAllocateCommandBuffers(vk->device, &ai, &cmd) != VK_SUCCESS) {
		return false;
	}

	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vk->vkBeginCommandBuffer(cmd, &bi);

	// Atlas: SHADER_READ_ONLY_OPTIMAL → TRANSFER_SRC_OPTIMAL.
	VkImageMemoryBarrier atlas_to_src = {};
	atlas_to_src.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	atlas_to_src.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
	atlas_to_src.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	atlas_to_src.oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	atlas_to_src.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	atlas_to_src.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	atlas_to_src.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	atlas_to_src.image = atlas_image;
	atlas_to_src.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};

	// Target: assume COLOR_ATTACHMENT_OPTIMAL (the compositor's pre-DP
	// barrier set this in the window-target path; for texture-mode the
	// shared image's layout is caller-dependent — we use UNDEFINED→
	// TRANSFER_DST which is always safe for clearing).
	VkImageMemoryBarrier target_to_dst = {};
	target_to_dst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	target_to_dst.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	target_to_dst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	target_to_dst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	target_to_dst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	target_to_dst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	target_to_dst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	target_to_dst.image = target_image;
	target_to_dst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};

	VkImageMemoryBarrier pre[2] = {atlas_to_src, target_to_dst};
	vk->vkCmdPipelineBarrier(cmd,
	    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	    VK_PIPELINE_STAGE_TRANSFER_BIT,
	    0, 0, nullptr, 0, nullptr, 2, pre);

	// Stretch-blit the atlas to fill the target. Linear filter so a
	// resolution mismatch doesn't go blocky.
	VkImageBlit blit = {};
	blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	blit.srcOffsets[0] = {0, 0, 0};
	blit.srcOffsets[1] = {(int32_t)atlas_width, (int32_t)atlas_height, 1};
	blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	blit.dstOffsets[0] = {0, 0, 0};
	blit.dstOffsets[1] = {(int32_t)target_width, (int32_t)target_height, 1};
	vk->vkCmdBlitImage(cmd,
	    atlas_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	    target_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
	    1, &blit, VK_FILTER_LINEAR);

	// Restore atlas to SHADER_READ for the compositor's invariant;
	// leave target in COLOR_ATTACHMENT_OPTIMAL (xrEndFrame's contract).
	VkImageMemoryBarrier atlas_back = atlas_to_src;
	atlas_back.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	atlas_back.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
	atlas_back.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	atlas_back.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	VkImageMemoryBarrier target_back = target_to_dst;
	target_back.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	target_back.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	target_back.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	target_back.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	VkImageMemoryBarrier post[2] = {atlas_back, target_back};
	vk->vkCmdPipelineBarrier(cmd,
	    VK_PIPELINE_STAGE_TRANSFER_BIT,
	    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	    0, 0, nullptr, 0, nullptr, 2, post);

	vk->vkEndCommandBuffer(cmd);

	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	VkResult res = vk->vkQueueSubmit(vk->main_queue->queue, 1, &si, VK_NULL_HANDLE);
	if (res == VK_SUCCESS) {
		vk->vkQueueWaitIdle(vk->main_queue->queue);
	}
	vk->vkFreeCommandBuffers(vk->device, impl->cmd_pool, 1, &cmd);
	DXR_HW_DBG_ONCE("mono_passthrough_blit: first frame (atlas %ux%u → target %ux%u)",
	                atlas_width, atlas_height, target_width, target_height);
	return res == VK_SUCCESS;
}

// Tear down the cached CNSDK weave destination (render pass + depth target +
// all per-image color views/framebuffers). Safe to call repeatedly.
void
destroy_weave_target(leia_dp_cnsdk *impl)
{
	struct vk_bundle *vk = impl->vk;
	if (vk == nullptr) {
		return;
	}
	for (uint32_t i = 0; i < impl->weave_fb_count; i++) {
		if (impl->weave_fb_cache[i].fb != VK_NULL_HANDLE) {
			vk->vkDestroyFramebuffer(vk->device, impl->weave_fb_cache[i].fb, nullptr);
		}
		// .view is borrowed (compositor-owned) — do NOT destroy it.
		impl->weave_fb_cache[i] = {};
	}
	impl->weave_fb_count = 0;
	if (impl->weave_depth_view != VK_NULL_HANDLE) {
		vk->vkDestroyImageView(vk->device, impl->weave_depth_view, nullptr);
		impl->weave_depth_view = VK_NULL_HANDLE;
	}
	if (impl->weave_depth_img != VK_NULL_HANDLE) {
		vk->vkDestroyImage(vk->device, impl->weave_depth_img, nullptr);
		impl->weave_depth_img = VK_NULL_HANDLE;
	}
	if (impl->weave_depth_mem != VK_NULL_HANDLE) {
		vk->vkFreeMemory(vk->device, impl->weave_depth_mem, nullptr);
		impl->weave_depth_mem = VK_NULL_HANDLE;
	}
	if (impl->weave_rp != VK_NULL_HANDLE) {
		vk->vkDestroyRenderPass(vk->device, impl->weave_rp, nullptr);
		impl->weave_rp = VK_NULL_HANDLE;
	}
	impl->weave_w = 0;
	impl->weave_h = 0;
	impl->weave_color_fmt = VK_FORMAT_UNDEFINED;
}

// One-shot transition of the depth target into DEPTH_STENCIL_ATTACHMENT_OPTIMAL
// so CNSDK's interlace render pass (LOAD + that initialLayout, per CNSDK's own
// Vulkan sample) is satisfied. Depth contents are unused (interlace is a
// fullscreen pass) — only the layout must match.
void
transition_weave_depth_once(leia_dp_cnsdk *impl)
{
	struct vk_bundle *vk = impl->vk;
	if (vk->main_queue == nullptr) {
		return;
	}
	VkCommandBufferAllocateInfo ai = {};
	ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	ai.commandPool = impl->cmd_pool;
	ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	ai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vk->vkAllocateCommandBuffers(vk->device, &ai, &cmd) != VK_SUCCESS) {
		return;
	}
	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vk->vkBeginCommandBuffer(cmd, &bi);
	VkImageMemoryBarrier b = {};
	b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	b.srcAccessMask = 0;
	b.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
	b.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	b.newLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
	b.image = impl->weave_depth_img;
	b.subresourceRange = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
	vk->vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
	    VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
	vk->vkEndCommandBuffer(cmd);
	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	if (vk->vkQueueSubmit(vk->main_queue->queue, 1, &si, VK_NULL_HANDLE) == VK_SUCCESS) {
		vk->vkQueueWaitIdle(vk->main_queue->queue);
	}
	vk->vkFreeCommandBuffers(vk->device, impl->cmd_pool, 1, &cmd);
}

// Build (once per w/h/format) the CNSDK-compatible destination render pass
// (color + depth) and depth target. Render-pass compatibility is format-based,
// so matching the attachment formats CNSDK's interlacer was initialized with
// (color = target format, depth = D32_SFLOAT) lets its internal
// vkCmdBeginRenderPass accept a framebuffer we built. Mirrors CNSDK's own
// Vulkan sample (cnsdk/samples/leia/lwEngine/LWE_Core.cpp). Returns false on
// failure → the caller skips the weave that frame (never crashes the loop).
bool
ensure_weave_rp_and_depth(leia_dp_cnsdk *impl, uint32_t w, uint32_t h, VkFormat color_fmt)
{
	struct vk_bundle *vk = impl->vk;

	if (impl->weave_rp != VK_NULL_HANDLE && impl->weave_w == w &&
	    impl->weave_h == h && impl->weave_color_fmt == color_fmt) {
		return true;
	}
	// Params changed (e.g. orientation swap) — rebuild from scratch.
	destroy_weave_target(impl);

	VkAttachmentDescription color = {};
	color.format = color_fmt;
	color.samples = VK_SAMPLE_COUNT_1_BIT;
	color.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
	color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
	color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	color.initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	color.finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

	VkAttachmentDescription depth = {};
	depth.format = VK_FORMAT_D32_SFLOAT;
	depth.samples = VK_SAMPLE_COUNT_1_BIT;
	depth.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
	depth.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depth.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	depth.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	depth.initialLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
	depth.finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

	VkAttachmentReference color_ref = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
	VkAttachmentReference depth_ref = {1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};

	VkSubpassDescription subpass = {};
	subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
	subpass.colorAttachmentCount = 1;
	subpass.pColorAttachments = &color_ref;
	subpass.pDepthStencilAttachment = &depth_ref;

	VkSubpassDependency dep = {};
	dep.srcSubpass = VK_SUBPASS_EXTERNAL;
	dep.dstSubpass = 0;
	dep.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
	dep.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
	dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

	VkAttachmentDescription atts[2] = {color, depth};
	VkRenderPassCreateInfo rpci = {};
	rpci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
	rpci.attachmentCount = 2;
	rpci.pAttachments = atts;
	rpci.subpassCount = 1;
	rpci.pSubpasses = &subpass;
	rpci.dependencyCount = 1;
	rpci.pDependencies = &dep;
	if (vk->vkCreateRenderPass(vk->device, &rpci, nullptr, &impl->weave_rp) != VK_SUCCESS) {
		impl->weave_rp = VK_NULL_HANDLE;
		U_LOG_W("ensure_weave_rp_and_depth: vkCreateRenderPass failed");
		return false;
	}

	VkExtent2D ext = {w, h};
	if (vk_create_image_simple(vk, ext, VK_FORMAT_D32_SFLOAT,
	        VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
	        &impl->weave_depth_mem, &impl->weave_depth_img) != VK_SUCCESS) {
		U_LOG_W("ensure_weave_rp_and_depth: depth image create failed");
		destroy_weave_target(impl);
		return false;
	}
	VkImageSubresourceRange depth_range = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
	if (vk_create_view(vk, impl->weave_depth_img, VK_IMAGE_VIEW_TYPE_2D,
	        VK_FORMAT_D32_SFLOAT, depth_range, &impl->weave_depth_view) != VK_SUCCESS) {
		U_LOG_W("ensure_weave_rp_and_depth: depth view create failed");
		destroy_weave_target(impl);
		return false;
	}
	transition_weave_depth_once(impl);

	impl->weave_w = w;
	impl->weave_h = h;
	impl->weave_color_fmt = color_fmt;
	DXR_HW_DBG("weave target built: rp=%p depth=%p %ux%u colorFmt=%d",
	           (void *)impl->weave_rp, (void *)impl->weave_depth_img, w, h, (int)color_fmt);
	return true;
}

// Look up (or lazily create + cache) the destination framebuffer wrapping the
// compositor's color view (set via set_target_color_view) for the upcoming
// target image, plus our shared depth view. We build NO image views on
// swapchain images ourselves — the compositor owns those. Returns
// VK_NULL_HANDLE on failure (caller skips the weave).
VkFramebuffer
get_or_create_weave_fb(leia_dp_cnsdk *impl)
{
	struct vk_bundle *vk = impl->vk;
	VkImageView color_view = impl->pending_target_view;
	if (color_view == VK_NULL_HANDLE) {
		// Runtime didn't hand us a target view (older runtime without the
		// set_target_color_view slot). We can't safely mint our own on this
		// driver, so skip the weave this frame.
		DXR_HW_DBG_ONCE("get_or_create_weave_fb: no target view from compositor; skipping weave");
		return VK_NULL_HANDLE;
	}
	for (uint32_t i = 0; i < impl->weave_fb_count; i++) {
		if (impl->weave_fb_cache[i].view == color_view) {
			return impl->weave_fb_cache[i].fb;
		}
	}
	if (impl->weave_fb_count >= 8) {
		// The compositor recreated its swapchain (surface re-sync on a
		// background→resume cycle, runtime#528, or live rotation): every
		// cached entry references a view from a destroyed swapchain, so a
		// full cache on a miss means stale entries — flush and rebuild on
		// demand. The recreate idled the device, so the old framebuffers
		// are not in flight. (Previously this skipped the weave forever →
		// black panel after the second picker round-trip.)
		U_LOG_W("get_or_create_weave_fb: view set churned (swapchain recreate) — flushing fb cache");
		for (uint32_t i = 0; i < impl->weave_fb_count; i++) {
			if (impl->weave_fb_cache[i].fb != VK_NULL_HANDLE) {
				vk->vkDestroyFramebuffer(vk->device, impl->weave_fb_cache[i].fb, nullptr);
			}
			impl->weave_fb_cache[i] = {};
		}
		impl->weave_fb_count = 0;
	}
	VkImageView atts[2] = {color_view, impl->weave_depth_view};
	VkFramebufferCreateInfo fbci = {};
	fbci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
	fbci.renderPass = impl->weave_rp;
	fbci.attachmentCount = 2;
	fbci.pAttachments = atts;
	fbci.width = impl->weave_w;
	fbci.height = impl->weave_h;
	fbci.layers = 1;
	DXR_HW_DBG("weave fb create: rp=%p color_view=%p depth_view=%p %ux%u",
	           (void *)impl->weave_rp, (void *)color_view, (void *)impl->weave_depth_view,
	           impl->weave_w, impl->weave_h);
	VkFramebuffer fb = VK_NULL_HANDLE;
	if (vk->vkCreateFramebuffer(vk->device, &fbci, nullptr, &fb) != VK_SUCCESS) {
		U_LOG_W("get_or_create_weave_fb: vkCreateFramebuffer failed");
		return VK_NULL_HANDLE;
	}
	impl->weave_fb_cache[impl->weave_fb_count].view = color_view;
	impl->weave_fb_cache[impl->weave_fb_count].fb = fb;
	impl->weave_fb_count++;
	DXR_HW_DBG("weave fb cached[%u]: color_view=%p fb=%p", impl->weave_fb_count - 1,
	           (void *)color_view, (void *)fb);
	return fb;
}

// Compositor hands us the color view for the next process_atlas target.
void
set_target_color_view_cnsdk(struct xrt_display_processor *xdp, VkImageView color_view)
{
	as_impl(xdp)->pending_target_view = color_view;
}

// ─── Transparent-background alpha-gate (#568) ───────────────────────────────
//
// Ported from the desktop DP (src/drv_leia/leia_display_processor.cpp,
// alpha_gate_*) and its shaders/alpha_gate.frag. The CNSDK weave interlaces
// into opaque RGB — it DESTROYS per-pixel alpha — so transparency is
// RECONSTRUCTED with a fullscreen post-weave pass: sample the ORIGINAL
// premultiplied atlas, and for each output pixel write (0,0,0,0) iff every view
// tile is α==0 at the tile-local UV (else the woven RGB at α=1). SurfaceFlinger
// then composites the runtime's translucent surface over the home screen, so
// the holes show the live screen for free (the Android in-process model,
// ADR-025) — no chroma-key, no captured-background compose.
//
// Two divergences from the desktop port:
//   1. SELF-SUBMIT. The desktop records into the compositor's command buffer;
//      this CNSDK DP is self-submitting (cmd_buffer is VK_NULL_HANDLE, the weave
//      already submitted). So the gate allocates its OWN one-shot command buffer
//      and submits it (the mono_passthrough_blit idiom).
//   2. EXIT LAYOUT. The desktop's strip render pass ends in PRESENT_SRC_KHR
//      (its target entered as PRESENT_SRC). Here the CNSDK weave leaves the
//      target in COLOR_ATTACHMENT_OPTIMAL, so the gate's render pass ends there
//      too — the compositor/swapchain owns the present transition.

static VkShaderModule
ag_create_shader_module(struct vk_bundle *vk, const uint32_t *code, size_t code_size)
{
	VkShaderModuleCreateInfo ci = {};
	ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
	ci.codeSize = code_size;
	ci.pCode = code;
	VkShaderModule m = VK_NULL_HANDLE;
	if (vk->vkCreateShaderModule(vk->device, &ci, nullptr, &m) != VK_SUCCESS) {
		return VK_NULL_HANDLE;
	}
	return m;
}

// Tear down all alpha-gate resources. Safe to call repeatedly.
void
destroy_alpha_gate(leia_dp_cnsdk *impl)
{
	struct vk_bundle *vk = impl->vk;
	if (vk == nullptr) {
		return;
	}
	for (uint32_t i = 0; i < impl->ag_fb_count; i++) {
		if (impl->ag_fb_cache[i].fb != VK_NULL_HANDLE) {
			vk->vkDestroyFramebuffer(vk->device, impl->ag_fb_cache[i].fb, nullptr);
		}
		// .view is borrowed (compositor-owned) — do NOT destroy it.
		impl->ag_fb_cache[i] = {};
	}
	impl->ag_fb_count = 0;
	if (impl->ag_strip_view != VK_NULL_HANDLE) {
		vk->vkDestroyImageView(vk->device, impl->ag_strip_view, nullptr);
		impl->ag_strip_view = VK_NULL_HANDLE;
	}
	if (impl->ag_strip_img != VK_NULL_HANDLE) {
		vk->vkDestroyImage(vk->device, impl->ag_strip_img, nullptr);
		impl->ag_strip_img = VK_NULL_HANDLE;
	}
	if (impl->ag_strip_mem != VK_NULL_HANDLE) {
		vk->vkFreeMemory(vk->device, impl->ag_strip_mem, nullptr);
		impl->ag_strip_mem = VK_NULL_HANDLE;
	}
	impl->ag_strip_w = 0;
	impl->ag_strip_h = 0;
	if (impl->ag_pipeline != VK_NULL_HANDLE) {
		vk->vkDestroyPipeline(vk->device, impl->ag_pipeline, nullptr);
		impl->ag_pipeline = VK_NULL_HANDLE;
	}
	if (impl->ag_desc_pool != VK_NULL_HANDLE) {
		vk->vkDestroyDescriptorPool(vk->device, impl->ag_desc_pool, nullptr);
		impl->ag_desc_pool = VK_NULL_HANDLE;
		impl->ag_set = VK_NULL_HANDLE; // freed with the pool
	}
	if (impl->ag_pipeline_layout != VK_NULL_HANDLE) {
		vk->vkDestroyPipelineLayout(vk->device, impl->ag_pipeline_layout, nullptr);
		impl->ag_pipeline_layout = VK_NULL_HANDLE;
	}
	if (impl->ag_desc_layout != VK_NULL_HANDLE) {
		vk->vkDestroyDescriptorSetLayout(vk->device, impl->ag_desc_layout, nullptr);
		impl->ag_desc_layout = VK_NULL_HANDLE;
	}
	if (impl->ag_rp != VK_NULL_HANDLE) {
		vk->vkDestroyRenderPass(vk->device, impl->ag_rp, nullptr);
		impl->ag_rp = VK_NULL_HANDLE;
	}
	if (impl->ag_sampler != VK_NULL_HANDLE) {
		vk->vkDestroySampler(vk->device, impl->ag_sampler, nullptr);
		impl->ag_sampler = VK_NULL_HANDLE;
	}
	impl->ag_inited = false;
	impl->ag_fmt = VK_FORMAT_UNDEFINED;
}

// Lazily build the alpha-gate pipeline + render pass + descriptor set (once per
// target format). Returns false on failure → the caller skips the gate.
bool
alpha_gate_ensure_pipeline(leia_dp_cnsdk *impl, VkFormat target_format)
{
	struct vk_bundle *vk = impl->vk;
	if (impl->ag_inited && impl->ag_fmt == target_format) {
		return true;
	}
	if (impl->ag_inited) {
		// Format changed (rare on Android) — rebuild from scratch.
		destroy_alpha_gate(impl);
	}

	VkResult res;

	// Linear/clamp sampler.
	{
		VkSamplerCreateInfo si = {};
		si.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
		si.magFilter = VK_FILTER_LINEAR;
		si.minFilter = VK_FILTER_LINEAR;
		si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
		si.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
		si.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
		si.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
		si.maxLod = 1.0f;
		res = vk->vkCreateSampler(vk->device, &si, nullptr, &impl->ag_sampler);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: sampler failed: %d", res);
			return false;
		}
	}

	// 3-binding descriptor set layout (backbuffer 0 + atlas 1 + backdrop 2).
	// Android has no Local2D under-layer (#491) yet, so binding 2 is always
	// bound to a dummy and has_backdrop is pushed as 0 — keeps the shader
	// byte-identical to the desktop's alpha_gate.frag.
	{
		VkDescriptorSetLayoutBinding bs[3] = {};
		for (uint32_t i = 0; i < 3; i++) {
			bs[i].binding = i;
			bs[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
			bs[i].descriptorCount = 1;
			bs[i].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
		}
		VkDescriptorSetLayoutCreateInfo ci = {};
		ci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
		ci.bindingCount = 3;
		ci.pBindings = bs;
		res = vk->vkCreateDescriptorSetLayout(vk->device, &ci, nullptr, &impl->ag_desc_layout);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: desc layout failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
	}

	// Pipeline layout: 32-byte push constant (uvec2 tile_count + uint has_backdrop
	// + uint mode + vec4 canvas — the canvas sub-rect for XR_EXT_display_zones, #568).
	{
		VkPushConstantRange pc = {};
		pc.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
		pc.offset = 0;
		pc.size = 32;
		VkPipelineLayoutCreateInfo pli = {};
		pli.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
		pli.setLayoutCount = 1;
		pli.pSetLayouts = &impl->ag_desc_layout;
		pli.pushConstantRangeCount = 1;
		pli.pPushConstantRanges = &pc;
		res = vk->vkCreatePipelineLayout(vk->device, &pli, nullptr, &impl->ag_pipeline_layout);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: pipeline layout failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
	}

	// Descriptor pool + 1 set.
	{
		VkDescriptorPoolSize size = {};
		size.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
		size.descriptorCount = 3;
		VkDescriptorPoolCreateInfo dpi = {};
		dpi.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
		dpi.maxSets = 1;
		dpi.poolSizeCount = 1;
		dpi.pPoolSizes = &size;
		res = vk->vkCreateDescriptorPool(vk->device, &dpi, nullptr, &impl->ag_desc_pool);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: desc pool failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
		VkDescriptorSetAllocateInfo ai = {};
		ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
		ai.descriptorPool = impl->ag_desc_pool;
		ai.descriptorSetCount = 1;
		ai.pSetLayouts = &impl->ag_desc_layout;
		res = vk->vkAllocateDescriptorSets(vk->device, &ai, &impl->ag_set);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: desc set alloc failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
	}

	// Output render pass: single color attachment in the target format. The gate
	// overwrites every pixel (fullscreen tri) so loadOp = DONT_CARE. finalLayout
	// = COLOR_ATTACHMENT_OPTIMAL to MATCH the CNSDK weave exit (xrEndFrame
	// contract) — NOT PRESENT_SRC_KHR.
	{
		VkAttachmentDescription att = {};
		att.format = target_format;
		att.samples = VK_SAMPLE_COUNT_1_BIT;
		att.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
		att.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
		att.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
		att.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
		att.initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
		att.finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
		VkAttachmentReference ref = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
		VkSubpassDescription sub = {};
		sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
		sub.colorAttachmentCount = 1;
		sub.pColorAttachments = &ref;
		VkRenderPassCreateInfo rpi = {};
		rpi.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
		rpi.attachmentCount = 1;
		rpi.pAttachments = &att;
		rpi.subpassCount = 1;
		rpi.pSubpasses = &sub;
		res = vk->vkCreateRenderPass(vk->device, &rpi, nullptr, &impl->ag_rp);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: render pass failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
	}

	// Pipeline.
	{
		VkShaderModule vs = ag_create_shader_module(vk, shaders_fullscreen_tri_vert,
		                                            sizeof(shaders_fullscreen_tri_vert));
		VkShaderModule fs = ag_create_shader_module(vk, shaders_alpha_gate_frag,
		                                            sizeof(shaders_alpha_gate_frag));
		if (vs == VK_NULL_HANDLE || fs == VK_NULL_HANDLE) {
			if (vs != VK_NULL_HANDLE) {
				vk->vkDestroyShaderModule(vk->device, vs, nullptr);
			}
			if (fs != VK_NULL_HANDLE) {
				vk->vkDestroyShaderModule(vk->device, fs, nullptr);
			}
			U_LOG_W("alpha-gate: shader module create failed");
			destroy_alpha_gate(impl);
			return false;
		}

		VkPipelineShaderStageCreateInfo stages[2] = {};
		stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
		stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
		stages[0].module = vs;
		stages[0].pName = "main";
		stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
		stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
		stages[1].module = fs;
		stages[1].pName = "main";

		VkPipelineVertexInputStateCreateInfo vi = {};
		vi.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
		VkPipelineInputAssemblyStateCreateInfo ia = {};
		ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
		ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
		VkPipelineViewportStateCreateInfo vps = {};
		vps.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
		vps.viewportCount = 1;
		vps.scissorCount = 1;
		VkPipelineRasterizationStateCreateInfo rs = {};
		rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
		rs.polygonMode = VK_POLYGON_MODE_FILL;
		rs.cullMode = VK_CULL_MODE_NONE;
		rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
		rs.lineWidth = 1.0f;
		VkPipelineMultisampleStateCreateInfo ms = {};
		ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
		ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
		// THE FOOTGUN (cost hours on Windows): blendEnable MUST be VK_FALSE and
		// all 4 channels written, so the (0,0,0,0) hole write lands verbatim. Under
		// an inherited src-over blend it would be a no-op and the holes never show.
		VkPipelineColorBlendAttachmentState ba = {};
		ba.blendEnable = VK_FALSE;
		ba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
		                    VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
		VkPipelineColorBlendStateCreateInfo cb = {};
		cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
		cb.attachmentCount = 1;
		cb.pAttachments = &ba;
		VkDynamicState dyn[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
		VkPipelineDynamicStateCreateInfo dynstate = {};
		dynstate.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
		dynstate.dynamicStateCount = 2;
		dynstate.pDynamicStates = dyn;
		VkGraphicsPipelineCreateInfo pi = {};
		pi.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
		pi.stageCount = 2;
		pi.pStages = stages;
		pi.pVertexInputState = &vi;
		pi.pInputAssemblyState = &ia;
		pi.pViewportState = &vps;
		pi.pRasterizationState = &rs;
		pi.pMultisampleState = &ms;
		pi.pColorBlendState = &cb;
		pi.pDynamicState = &dynstate;
		pi.layout = impl->ag_pipeline_layout;
		pi.renderPass = impl->ag_rp;
		pi.subpass = 0;
		res = vk->vkCreateGraphicsPipelines(vk->device, VK_NULL_HANDLE, 1, &pi, nullptr, &impl->ag_pipeline);
		vk->vkDestroyShaderModule(vk->device, fs, nullptr);
		vk->vkDestroyShaderModule(vk->device, vs, nullptr);
		if (res != VK_SUCCESS) {
			U_LOG_W("alpha-gate: pipeline create failed: %d", res);
			destroy_alpha_gate(impl);
			return false;
		}
	}

	impl->ag_fmt = target_format;
	impl->ag_inited = true;
	U_LOG_W("Leia CNSDK DP: alpha-gate pipeline ready (transparent background)");
	return true;
}

// Create or recreate the strip sampling image+view to match (w, h). The strip
// holds a copy of the woven target (you can't sample and render the same image).
bool
alpha_gate_ensure_strip(leia_dp_cnsdk *impl, uint32_t w, uint32_t h, VkFormat fmt)
{
	struct vk_bundle *vk = impl->vk;
	if (impl->ag_strip_img != VK_NULL_HANDLE && impl->ag_strip_w == w && impl->ag_strip_h == h) {
		return true;
	}
	if (impl->ag_strip_view != VK_NULL_HANDLE) {
		vk->vkDestroyImageView(vk->device, impl->ag_strip_view, nullptr);
		impl->ag_strip_view = VK_NULL_HANDLE;
	}
	if (impl->ag_strip_img != VK_NULL_HANDLE) {
		vk->vkDestroyImage(vk->device, impl->ag_strip_img, nullptr);
		impl->ag_strip_img = VK_NULL_HANDLE;
	}
	if (impl->ag_strip_mem != VK_NULL_HANDLE) {
		vk->vkFreeMemory(vk->device, impl->ag_strip_mem, nullptr);
		impl->ag_strip_mem = VK_NULL_HANDLE;
	}
	VkExtent2D ext = {w, h};
	VkImageUsageFlags usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
	if (vk_create_image_simple(vk, ext, fmt, usage, &impl->ag_strip_mem, &impl->ag_strip_img) != VK_SUCCESS) {
		U_LOG_W("alpha-gate: strip image create failed");
		return false;
	}
	VkImageSubresourceRange sub = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	if (vk_create_view(vk, impl->ag_strip_img, VK_IMAGE_VIEW_TYPE_2D, fmt, sub, &impl->ag_strip_view) != VK_SUCCESS) {
		U_LOG_W("alpha-gate: strip view create failed");
		return false;
	}
	impl->ag_strip_w = w;
	impl->ag_strip_h = h;
	return true;
}

// Get (or lazily create + cache) the output framebuffer for the upcoming target,
// wrapping the compositor's color view (pending_target_view) + ag_rp. We build
// NO image views on swapchain images ourselves (Adreno faults) — same contract
// as get_or_create_weave_fb. Returns VK_NULL_HANDLE on failure.
VkFramebuffer
alpha_gate_get_fb(leia_dp_cnsdk *impl, uint32_t w, uint32_t h)
{
	struct vk_bundle *vk = impl->vk;
	VkImageView color_view = impl->pending_target_view;
	if (color_view == VK_NULL_HANDLE) {
		return VK_NULL_HANDLE;
	}
	for (uint32_t i = 0; i < impl->ag_fb_count; i++) {
		if (impl->ag_fb_cache[i].view == color_view) {
			if (impl->ag_fb_cache[i].w == w && impl->ag_fb_cache[i].h == h) {
				return impl->ag_fb_cache[i].fb;
			}
			// Same view handle, different dims — the driver recycled a
			// destroyed view across a rotation (portrait⇄landscape). The
			// cached fb is the OLD orientation's size; rendering into it
			// shears the image (#568 landscape bug). Rebuild this entry at
			// the new dims.
			if (impl->ag_fb_cache[i].fb != VK_NULL_HANDLE) {
				vk->vkDestroyFramebuffer(vk->device, impl->ag_fb_cache[i].fb, nullptr);
				impl->ag_fb_cache[i].fb = VK_NULL_HANDLE;
			}
			VkFramebufferCreateInfo fbci2 = {};
			fbci2.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
			fbci2.renderPass = impl->ag_rp;
			fbci2.attachmentCount = 1;
			fbci2.pAttachments = &color_view;
			fbci2.width = w;
			fbci2.height = h;
			fbci2.layers = 1;
			VkFramebuffer rfb = VK_NULL_HANDLE;
			if (vk->vkCreateFramebuffer(vk->device, &fbci2, nullptr, &rfb) != VK_SUCCESS) {
				U_LOG_W("alpha-gate: framebuffer rebuild (rotation) failed");
				return VK_NULL_HANDLE;
			}
			impl->ag_fb_cache[i].fb = rfb;
			impl->ag_fb_cache[i].w = w;
			impl->ag_fb_cache[i].h = h;
			U_LOG_W("alpha-gate: rebuilt fb for recycled view at new dims %ux%u (rotation guard, #568)", w, h);
			return rfb;
		}
	}
	if (impl->ag_fb_count >= 8) {
		// Swapchain recreate churned the compositor's view set — flush and
		// rebuild on demand (the recreate idled the device, so old FBs aren't
		// in flight). Same rationale as get_or_create_weave_fb.
		for (uint32_t i = 0; i < impl->ag_fb_count; i++) {
			if (impl->ag_fb_cache[i].fb != VK_NULL_HANDLE) {
				vk->vkDestroyFramebuffer(vk->device, impl->ag_fb_cache[i].fb, nullptr);
			}
			impl->ag_fb_cache[i] = {};
		}
		impl->ag_fb_count = 0;
	}
	VkFramebufferCreateInfo fbci = {};
	fbci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
	fbci.renderPass = impl->ag_rp;
	fbci.attachmentCount = 1;
	fbci.pAttachments = &color_view;
	fbci.width = w;
	fbci.height = h;
	fbci.layers = 1;
	VkFramebuffer fb = VK_NULL_HANDLE;
	if (vk->vkCreateFramebuffer(vk->device, &fbci, nullptr, &fb) != VK_SUCCESS) {
		U_LOG_W("alpha-gate: framebuffer create failed");
		return VK_NULL_HANDLE;
	}
	impl->ag_fb_cache[impl->ag_fb_count].view = color_view;
	impl->ag_fb_cache[impl->ag_fb_count].fb = fb;
	impl->ag_fb_cache[impl->ag_fb_count].w = w;
	impl->ag_fb_cache[impl->ag_fb_count].h = h;
	impl->ag_fb_count++;
	return fb;
}

// Alpha-gate mode (#568), read once from `debug.dxr.alphagate`:
//   1 (default) = woven per-pixel view-select — makes the parallax
//                 de-occlusion band see-through (the fix).
//   0           = legacy all-or-nothing mask (kept for on-device A/B; this is
//                 the mode that produced the black de-occlusion fringe).
// Cached because __system_property_get isn't free and a mid-session flip would
// race in-flight frames; force-stop the app to re-read.
uint32_t
alpha_gate_mode()
{
	static uint32_t cached = UINT32_MAX;
	if (cached != UINT32_MAX) {
		return cached;
	}
	cached = 1u; // default: the fix
#ifdef XRT_OS_ANDROID
	char buf[PROP_VALUE_MAX] = {0};
	if (__system_property_get("debug.dxr.alphagate", buf) > 0 && buf[0] == '0') {
		cached = 0u;
	}
#endif
	U_LOG_W("Leia CNSDK DP: alpha-gate mode=%u (1=woven-select, 0=legacy)", cached);
	return cached;
}

// Post-weave alpha-gate executor. Self-submits (the weave already submitted on
// its own command buffer). target_image is in COLOR_ATTACHMENT_OPTIMAL on entry
// and on exit.
void
alpha_gate_run(leia_dp_cnsdk *impl,
               VkImage target_image,
               VkImageView atlas_view,
               uint32_t w,
               uint32_t h,
               uint32_t tile_columns,
               uint32_t tile_rows,
               VkFormat target_format,
               int32_t canvas_offset_x,
               int32_t canvas_offset_y,
               uint32_t canvas_width,
               uint32_t canvas_height)
{
	DXR_ATRACE("dxr_dp:alpha_gate_run");
	struct vk_bundle *vk = impl->vk;
	if (vk->main_queue == nullptr) {
		return;
	}
	if (!alpha_gate_ensure_pipeline(impl, target_format)) {
		return;
	}
	if (!alpha_gate_ensure_strip(impl, w, h, target_format)) {
		return;
	}
	VkFramebuffer fb = alpha_gate_get_fb(impl, w, h);
	if (fb == VK_NULL_HANDLE) {
		return;
	}

	// Always-on diagnostic, re-logged whenever the geometry changes (e.g. on a
	// portrait⇄landscape rotation, #568) so a device log shows exactly what the
	// gate sampled in each orientation. The gate is driven entirely by these
	// per-frame target + tile dims — no worst-case/portrait assumptions.
	{
		static uint32_t last_w = 0, last_h = 0, last_c = 0, last_r = 0;
		if (w != last_w || h != last_h || tile_columns != last_c || tile_rows != last_r) {
			last_w = w; last_h = h; last_c = tile_columns; last_r = tile_rows;
			U_LOG_W("AG_GEO: target=%ux%u tiles=%ux%u mode=%u (strip+fb+viewport all driven by this target)",
			        w, h, tile_columns, tile_rows, alpha_gate_mode());
		}
	}

	// The CNSDK weave self-submitted (possibly on its own queue); drain ALL
	// queues so its color-attachment writes to target_image are complete +
	// visible before we copy/sample it. A full device idle is the simplest
	// correct fence (the mono path + destroy use the same hammer); replacing it
	// with a weave-completion semaphore is a future optimization.
	vk->vkDeviceWaitIdle(vk->device);

	// Descriptors: 0 = strip copy (woven backbuffer), 1 = original premultiplied
	// atlas, 2 = dummy backdrop (= strip view; has_backdrop pushed 0 — no Local2D
	// under-layer on Android yet). The atlas is already SHADER_READ_ONLY_OPTIMAL
	// (compositor invariant; CNSDK only sampled it).
	VkDescriptorImageInfo infos[3] = {};
	infos[0].sampler = impl->ag_sampler;
	infos[0].imageView = impl->ag_strip_view;
	infos[0].imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	infos[1].sampler = impl->ag_sampler;
	infos[1].imageView = atlas_view;
	infos[1].imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	infos[2].sampler = impl->ag_sampler;
	infos[2].imageView = impl->ag_strip_view; // dummy
	infos[2].imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	VkWriteDescriptorSet writes[3] = {};
	for (uint32_t i = 0; i < 3; i++) {
		writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
		writes[i].dstSet = impl->ag_set;
		writes[i].dstBinding = i;
		writes[i].descriptorCount = 1;
		writes[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
		writes[i].pImageInfo = &infos[i];
	}
	vk->vkUpdateDescriptorSets(vk->device, 3, writes, 0, nullptr);

	// One-shot command buffer (self-submit; compositor's cmd is VK_NULL_HANDLE).
	VkCommandBufferAllocateInfo cbai = {};
	cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
	cbai.commandPool = impl->cmd_pool;
	cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
	cbai.commandBufferCount = 1;
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	if (vk->vkAllocateCommandBuffers(vk->device, &cbai, &cmd) != VK_SUCCESS) {
		return;
	}
	VkCommandBufferBeginInfo bi = {};
	bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
	bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
	vk->vkBeginCommandBuffer(cmd, &bi);

	// target COLOR_ATTACHMENT_OPTIMAL (weave exit) → TRANSFER_SRC;
	// strip UNDEFINED → TRANSFER_DST.
	VkImageMemoryBarrier pre[2] = {};
	pre[0].sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	pre[0].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	pre[0].dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	pre[0].oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	pre[0].newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	pre[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	pre[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	pre[0].image = target_image;
	pre[0].subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	pre[1].sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	pre[1].srcAccessMask = 0;
	pre[1].dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	pre[1].oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	pre[1].newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	pre[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	pre[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	pre[1].image = impl->ag_strip_img;
	pre[1].subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	vk->vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	    VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 2, pre);

	VkImageCopy region = {};
	region.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	region.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
	region.extent = {w, h, 1};
	vk->vkCmdCopyImage(cmd, target_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	    impl->ag_strip_img, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

	// target TRANSFER_SRC → COLOR_ATTACHMENT (gate draws into it);
	// strip TRANSFER_DST → SHADER_READ (sampled as backbuffer).
	VkImageMemoryBarrier mid[2] = {};
	mid[0].sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	mid[0].srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
	mid[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	mid[0].oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
	mid[0].newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
	mid[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	mid[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	mid[0].image = target_image;
	mid[0].subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	mid[1].sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
	mid[1].srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
	mid[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
	mid[1].oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
	mid[1].newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	mid[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	mid[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
	mid[1].image = impl->ag_strip_img;
	mid[1].subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
	vk->vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
	    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
	    0, 0, nullptr, 0, nullptr, 2, mid);

	VkRenderPassBeginInfo rpbi = {};
	rpbi.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
	rpbi.renderPass = impl->ag_rp;
	rpbi.framebuffer = fb;
	rpbi.renderArea.offset = {0, 0};
	rpbi.renderArea.extent = {w, h};
	vk->vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

	vk->vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, impl->ag_pipeline);
	vk->vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, impl->ag_pipeline_layout, 0, 1,
	    &impl->ag_set, 0, nullptr);

	struct {
		uint32_t tile_count[2];
		uint32_t has_backdrop;
		uint32_t mode;
		float    canvas[4];   // normalized (offset.x, offset.y, extent.x, extent.y)
	} push = {};
	push.tile_count[0] = tile_columns;
	push.tile_count[1] = tile_rows;
	push.has_backdrop = 0u;            // no Local2D under-layer on Android yet (#491)
	push.mode = alpha_gate_mode();     // #568: 1=woven view-select (de-occlusion fix), 0=legacy
	// XR_EXT_display_zones (#568): the canvas sub-rect the weave occupies, in
	// normalized target coords. A zero/empty rect means the content fills the
	// target → (0,0,1,1), the identity that reproduces the pre-zone behavior.
	if (canvas_width > 0u && canvas_height > 0u && w > 0u && h > 0u) {
		push.canvas[0] = (float)canvas_offset_x / (float)w;
		push.canvas[1] = (float)canvas_offset_y / (float)h;
		push.canvas[2] = (float)canvas_width   / (float)w;
		push.canvas[3] = (float)canvas_height  / (float)h;
	} else {
		push.canvas[0] = 0.0f; push.canvas[1] = 0.0f;
		push.canvas[2] = 1.0f; push.canvas[3] = 1.0f;
	}
	vk->vkCmdPushConstants(cmd, impl->ag_pipeline_layout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(push), &push);

	VkViewport vp = {0.0f, 0.0f, (float)w, (float)h, 0.0f, 1.0f};
	VkRect2D sc = {{0, 0}, {w, h}};
	vk->vkCmdSetViewport(cmd, 0, 1, &vp);
	vk->vkCmdSetScissor(cmd, 0, 1, &sc);
	vk->vkCmdDraw(cmd, 3, 1, 0, 0);
	vk->vkCmdEndRenderPass(cmd);

	vk->vkEndCommandBuffer(cmd);
	VkSubmitInfo si = {};
	si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
	si.commandBufferCount = 1;
	si.pCommandBuffers = &cmd;
	if (vk->vkQueueSubmit(vk->main_queue->queue, 1, &si, VK_NULL_HANDLE) == VK_SUCCESS) {
		vk->vkQueueWaitIdle(vk->main_queue->queue);
	}
	vk->vkFreeCommandBuffers(vk->device, impl->cmd_pool, 1, &cmd);
	DXR_HW_DBG_ONCE("alpha_gate_run: first gated frame (%ux%u tiles=%ux%u)", w, h, tile_columns, tile_rows);
}

// #568: session transparency enable (the VK/Android DP variant's appended slot).
// On Android client_presents is always true — SurfaceFlinger composites the
// runtime's translucent surface over the home screen — so the DP only
// reconstructs alpha (the post-weave gate) and never composes a captured
// background. Stored here; the gate runs in process_atlas_weave when set.
void
set_transparent_background_cnsdk(struct xrt_display_processor_vk *xdp, bool enabled, bool client_presents)
{
	leia_dp_cnsdk *impl = reinterpret_cast<leia_dp_cnsdk *>(xdp); // dp_vk is at offset 0
	impl->transparent_bg_enabled = enabled;
	impl->client_present_mode = client_presents;
	U_LOG_W("Leia CNSDK DP: transparent_background=%d (client_presents=%d)", enabled ? 1 : 0,
	        client_presents ? 1 : 0);
}

void
process_atlas_weave(struct xrt_display_processor *xdp,
                    VkCommandBuffer cmd_buffer,
                    VkImage_XDP atlas_image,
                    VkImageView atlas_view,
                    uint32_t view_width,
                    uint32_t view_height,
                    uint32_t tile_columns,
                    uint32_t tile_rows,
                    VkFormat_XDP view_format,
                    VkFramebuffer target_fb,
                    VkImage_XDP target_image,
                    uint32_t target_width,
                    uint32_t target_height,
                    VkFormat_XDP target_format,
                    int32_t canvas_offset_x,
                    int32_t canvas_offset_y,
                    uint32_t canvas_width,
                    uint32_t canvas_height)
{
	DXR_ATRACE("dxr_dp:process_atlas_weave");
	(void)cmd_buffer;     // self-submitting: compositor passes VK_NULL_HANDLE
	(void)view_format;
	(void)target_fb;      // self-submit: compositor has no CNSDK-compatible FB; we build our own

	// XR_EXT_display_zones (#568): a zone layer confines the woven output to a
	// canvas sub-rect (e.g. the avatar's bottom-75% tiger band). A zero/empty
	// rect means "fill the target" — collapse it to the full target so the weave
	// viewport + alpha-gate canvas are uniform downstream.
	const bool canvas_subrect = canvas_width > 0u && canvas_height > 0u &&
	                            (canvas_offset_x != 0 || canvas_offset_y != 0 ||
	                             canvas_width != target_width || canvas_height != target_height);

	leia_dp_cnsdk *impl = as_impl(xdp);

	if (tile_columns == 1 && tile_rows == 1) {
		// Mono / 2D mode: no interlacing needed. Atlas IS the final
		// image; blit it directly to the target so we still produce
		// something visible. CNSDK doesn't weave here (would be wrong
		// for 1x1) — only used in the runtime's 2D fallback or for
		// non-3D-display vendors. Implementation moved below for
		// readability.
		if (impl->vk == nullptr || impl->cmd_pool == VK_NULL_HANDLE) {
			return;
		}
		const uint32_t atlas_w_mono = view_width;
		const uint32_t atlas_h_mono = view_height;
		mono_passthrough_blit(impl, (VkImage)(uintptr_t)atlas_image,
		                      atlas_w_mono, atlas_h_mono,
		                      (VkImage)(uintptr_t)target_image,
		                      target_width, target_height);
		return;
	}
	if (tile_columns != 2 || tile_rows != 1) {
		static bool warned = false;
		if (!warned) {
			U_LOG_W("CNSDK DP expects 2x1 SBS atlas or 1x1 mono, got %ux%u; skipping",
			        tile_columns, tile_rows);
			warned = true;
		}
		return;
	}

	if (impl->vk == nullptr) {
		return;
	}

	// Gate the weave on CNSDK interlacer readiness. Async core init may
	// take several frames; until then the interlacer doesn't exist and
	// leia_cnsdk_weave is a no-op. The compositor's pre-DP submit has
	// already happened, so target is in COLOR_ATTACHMENT_OPTIMAL with
	// undefined content for those frames — acceptable for POC.
	if (!leia_cnsdk_ensure_interlacer(impl->cnsdk,
	                                   impl->vk->device,
	                                   impl->vk->physical_device,
	                                   (VkFormat)target_format)) {
		return;
	}
	DXR_HW_DBG_ONCE("process_atlas_weave: first frame with ready interlacer");

	// Build the CNSDK destination framebuffer (color + depth). The
	// compositor's target_fb is NULL for a self-submitting DP — CNSDK needs
	// a framebuffer compatible with its internal interlace render pass, which
	// only we can construct (it requires a depth attachment the compositor
	// has no knowledge of). Skip the weave (don't crash) if it can't be built.
	if (!ensure_weave_rp_and_depth(impl, target_width, target_height, (VkFormat)target_format)) {
		return;
	}
	VkFramebuffer dest_fb = get_or_create_weave_fb(impl);
	if (dest_fb == VK_NULL_HANDLE) {
		return;
	}

	const uint32_t atlas_w = view_width * tile_columns;
	const uint32_t atlas_h = view_height * tile_rows;

	{
		// HW-2c-geo diagnostic: dump the exact geometry handed to CNSDK once.
		// Ghosting + wrong-aspect together would show up here as a per-view
		// aspect that doesn't match a real eye image or a tile/atlas mismatch.
		static bool logged = false;
		if (!logged) {
			logged = true;
			U_LOG_W("HW_GEO: view=%ux%u (aspect %.3f) tiles=%ux%u atlas=%ux%u target=%ux%u fmt=%d",
			        view_width, view_height,
			        view_height ? (float)view_width / (float)view_height : 0.0f,
			        tile_columns, tile_rows, atlas_w, atlas_h, target_width, target_height,
			        (int)target_format);
		}
	}

#ifdef XRT_DEBUG_ANDROID_VERBOSE
	static int dp_dbg_frame = 0;
	if ((dp_dbg_frame++ % 60) == 0) {
		DXR_HW_DBG("process_atlas_weave[frame=%d]: atlas=%ux%u target=%ux%u fmt=%d",
		           dp_dbg_frame, atlas_w, atlas_h, target_width, target_height, (int)target_format);
	}
#endif

	leia_cnsdk_weave(impl->cnsdk,
	                 impl->vk->device,
	                 impl->vk->physical_device,
	                 (VkImage)(uintptr_t)atlas_image,
	                 atlas_view,
	                 atlas_w,
	                 atlas_h,
	                 (VkFormat)target_format,
	                 target_width,
	                 target_height,
	                 dest_fb,
	                 (VkImage)(uintptr_t)target_image,
	                 canvas_subrect ? canvas_offset_x : 0,
	                 canvas_subrect ? canvas_offset_y : 0,
	                 canvas_subrect ? canvas_width    : 0u,
	                 canvas_subrect ? canvas_height   : 0u);

	// #568: the weave interlaced into opaque RGB — reconstruct per-pixel alpha
	// so SurfaceFlinger shows the live screen through the transparent regions.
	// Gated on the session transparency flag + a 2x1 multiview grid (the only
	// layout the alpha-gate UV math handles; the mono 1x1 path returned above).
	if (impl->transparent_bg_enabled && tile_columns == 2 && tile_rows == 1) {
		// The gate runs over the WHOLE target: inside the canvas band it
		// reconstructs the woven view-select alpha; outside it punches fully
		// transparent (clearing whatever CNSDK left beyond its viewport). When
		// there is no sub-rect it passes 0s → the gate treats it as full-target.
		alpha_gate_run(impl, (VkImage)(uintptr_t)target_image, atlas_view, target_width,
		               target_height, tile_columns, tile_rows, (VkFormat)target_format,
		               canvas_subrect ? canvas_offset_x : 0,
		               canvas_subrect ? canvas_offset_y : 0,
		               canvas_subrect ? canvas_width    : 0u,
		               canvas_subrect ? canvas_height   : 0u);
	}
}

bool
is_self_submitting_true(struct xrt_display_processor *xdp)
{
	(void)xdp;
	return true;
}

// Try to fetch CNSDK's predicted face position and derive L/R eyes from
// it (face X ± IPD/2). Falls back to a hardcoded IPD-only stub if face
// tracking isn't running yet (CNSDK core still async-initializing, or
// no face lock).
bool
get_predicted_eye_positions_ipd(struct xrt_display_processor *xdp,
                                 struct xrt_eye_positions *out_eye_pos)
{
	leia_dp_cnsdk *impl = as_impl(xdp);

	bool tracked = false;
	float fx = 0.0f, fy = 0.0f, fz = kEyeViewerDistM;
	if (impl->cnsdk != nullptr) {
		if (leia_cnsdk_ensure_face_tracking_started(impl->cnsdk) &&
		    leia_cnsdk_get_primary_face(impl->cnsdk, &fx, &fy, &fz)) {
			tracked = true;
		}
	}

	out_eye_pos->eyes[0].x = fx - kIpdHalfM;
	out_eye_pos->eyes[0].y = fy;
	out_eye_pos->eyes[0].z = fz;
	out_eye_pos->eyes[1].x = fx + kIpdHalfM;
	out_eye_pos->eyes[1].y = fy;
	out_eye_pos->eyes[1].z = fz;
	out_eye_pos->count = 2;
	out_eye_pos->valid = true;
	out_eye_pos->is_tracking = tracked;
	return true;
}

bool
get_display_dimensions_default(struct xrt_display_processor *xdp,
                                float *out_width_m,
                                float *out_height_m)
{
	leia_dp_cnsdk *impl = as_impl(xdp);

	if (impl->cnsdk != nullptr &&
	    leia_cnsdk_get_display_metrics(impl->cnsdk, out_width_m, out_height_m,
	                                    nullptr, nullptr)) {
		return true;
	}

	*out_width_m = kDefaultDisplayWidthM;
	*out_height_m = kDefaultDisplayHeightM;
	return true;
}

bool
get_display_pixel_info_default(struct xrt_display_processor *xdp,
                                uint32_t *out_pixel_width,
                                uint32_t *out_pixel_height,
                                int32_t *out_screen_left,
                                int32_t *out_screen_top)
{
	leia_dp_cnsdk *impl = as_impl(xdp);

	*out_screen_left = 0;
	*out_screen_top = 0;

	if (impl->cnsdk != nullptr &&
	    leia_cnsdk_get_display_metrics(impl->cnsdk, nullptr, nullptr,
	                                    out_pixel_width, out_pixel_height)) {
		return true;
	}

	*out_pixel_width = kDefaultDisplayPixelW;
	*out_pixel_height = kDefaultDisplayPixelH;
	return true;
}

void
on_pause_cnsdk(struct xrt_display_processor *xdp)
{
	leia_dp_cnsdk *impl = as_impl(xdp);
	if (impl->cnsdk != nullptr) {
		leia_cnsdk_on_pause(impl->cnsdk);
	}
}

void
on_resume_cnsdk(struct xrt_display_processor *xdp)
{
	leia_dp_cnsdk *impl = as_impl(xdp);
	if (impl->cnsdk != nullptr) {
		leia_cnsdk_on_resume(impl->cnsdk);
	}
}

// #522: the runtime's MANAGED/MANUAL selection. Forward to the CNSDK wrapper,
// which toggles NoFaceMode (with the licensing/availability guard).
void
set_eye_tracking_mode_cnsdk(struct xrt_display_processor *xdp, uint32_t mode)
{
	leia_dp_cnsdk *impl = as_impl(xdp);
	if (impl->cnsdk != nullptr) {
		leia_cnsdk_set_eye_tracking_mode(impl->cnsdk, mode);
	}
}

void
destroy_impl(struct xrt_display_processor *xdp)
{
	leia_dp_cnsdk *impl = as_impl(xdp);

	// Drain all in-flight GPU work (especially CNSDK's interlacer
	// submits) before destroying any handles CNSDK might still be
	// reading. Same defensive idiom as audit B6 — applies in atlas mode
	// because CNSDK still owns its own queue submit even though we
	// don't have a per-view image / blit cmd buffer to wait on.
	if (impl->vk != nullptr) {
		impl->vk->vkDeviceWaitIdle(impl->vk->device);
	}

	// Destroy CNSDK first (it may still reference our framebuffers via its
	// interlacer), then our weave destination (render pass + depth + cached
	// per-image views/framebuffers). Both are after the device-idle above.
	if (impl->cnsdk != nullptr) {
		leia_cnsdk_destroy(&impl->cnsdk);
	}
	destroy_weave_target(impl);
	destroy_alpha_gate(impl); // #568
	free(impl);
}

} // namespace

extern "C" xrt_result_t
leia_dp_factory_cnsdk(void *vk_bundle,
                      void *vk_cmd_pool,
                      void *window_handle,
                      int32_t target_format,
                      struct xrt_display_processor **out_xdp)
{
	(void)window_handle; (void)target_format;

	struct leia_cnsdk *cnsdk = nullptr;
	xrt_result_t ret = leia_cnsdk_create(&cnsdk);
	if (ret != XRT_SUCCESS || cnsdk == nullptr) {
		U_LOG_W("leia_cnsdk_create failed (%d), falling back to no-DP path", (int)ret);
		return ret != XRT_SUCCESS ? ret : XRT_ERROR_DEVICE_CREATION_FAILED;
	}

	leia_dp_cnsdk *impl = static_cast<leia_dp_cnsdk *>(calloc(1, sizeof(*impl)));
	if (impl == nullptr) {
		leia_cnsdk_destroy(&cnsdk);
		return XRT_ERROR_ALLOCATION;
	}

	impl->cnsdk = cnsdk;
	impl->vk = static_cast<struct vk_bundle *>(vk_bundle);
	impl->cmd_pool = (VkCommandPool)(uintptr_t)vk_cmd_pool;

	/* ABI major v2 (ADR-020): the 8-byte struct_size header tells the
	 * runtime how far this vtable extends. The runtime gates every optional
	 * slot below on XRT_DP_HAS_SLOT(xdp, field), bounded against this value —
	 * leave it 0 (calloc default) and is_self_submitting / on_pause / on_resume /
	 * eye-positions / display-dims all read as absent, silently regressing the
	 * self-submitting atlas path into a double-submit.
	 *
	 * #568: report sizeof(struct xrt_display_processor_vk), NOT sizeof(base),
	 * so the runtime also discovers the appended set_transparent_background slot
	 * (the VK/Android DP variant — the struct_size gate is the discriminator). */
	impl->dp_vk.base.struct_size = static_cast<uint32_t>(sizeof(struct xrt_display_processor_vk));
	impl->dp_vk.base.process_atlas = process_atlas_weave;
	impl->dp_vk.base.on_pause = on_pause_cnsdk;
	impl->dp_vk.base.on_resume = on_resume_cnsdk;
	impl->dp_vk.base.is_self_submitting = is_self_submitting_true;
	impl->dp_vk.base.set_target_color_view = set_target_color_view_cnsdk;
	impl->dp_vk.base.get_predicted_eye_positions = get_predicted_eye_positions_ipd;
	impl->dp_vk.base.get_display_dimensions = get_display_dimensions_default;
	impl->dp_vk.base.get_display_pixel_info = get_display_pixel_info_default;
	impl->dp_vk.base.set_eye_tracking_mode = set_eye_tracking_mode_cnsdk; // #522
	impl->dp_vk.base.destroy = destroy_impl;
	impl->dp_vk.set_transparent_background = set_transparent_background_cnsdk; // #568 (variant slot)

	*out_xdp = &impl->dp_vk.base;

	U_LOG_W("Leia CNSDK DP created (atlas mode)");
	DXR_HW_DBG("factory: impl=%p vk=%p cnsdk=%p", (void *)impl, (void *)impl->vk, (void *)impl->cnsdk);
	return XRT_SUCCESS;
}
