# Copyright 2026, Leia Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Fetch the NeurD public headers from the PRIVATE LeiaInc/media_sdk repo at a
# pinned ref, for the plug-in's 2D->3D lift module (docs/lift-neurd.md).
#
# These headers are Leia-private: they land in a gitignored directory
# (NeurD-SDK-<ref>/include, see .gitignore) and must never be committed or
# re-hosted on this public repo -- same rule as the SR SDK.
#
# Auth: `gh` with an account (or GH_TOKEN) that can read LeiaInc/media_sdk.
# CI passes secrets.LEIALOFT_GITHUB_TOKEN, the token the SR SDK fetch uses.
#
# Exit 0 = headers ready; 1 = fetch failed. Callers treat failure as SOFT:
# the lift module compiles out and the rest of the plug-in builds unchanged.
#
# Usage: fetch-neurd-headers.ps1 -Repo LeiaInc/media_sdk -Ref v0.4.6 -Dest <dir>

param(
    [Parameter(Mandatory = $true)][string]$Repo,
    [Parameter(Mandatory = $true)][string]$Ref,
    [Parameter(Mandatory = $true)][string]$Dest
)

$ErrorActionPreference = 'Stop'
$inc = Join-Path $Dest 'include'

function Get-RepoFile([string]$path) {
    # Raw file contents at the pinned ref. gh exits non-zero on 404 / no auth.
    $out = & gh api "repos/$Repo/contents/${path}?ref=$Ref" -H 'Accept: application/vnd.github.raw' 2>&1
    if ($LASTEXITCODE -ne 0) { throw "gh api $path@$Ref failed: $out" }
    return ($out -join "`n") + "`n"
}

try {
    New-Item -ItemType Directory -Force $inc | Out-Null

    # NeurD.h includes NeurD_version.h and _NeurD_detail.h; the latter includes
    # _NeurD_table.h. That is the whole closure.
    foreach ($f in @('NeurD.h', '_NeurD_detail.h', '_NeurD_table.h')) {
        Set-Content -Path (Join-Path $inc $f) -Value (Get-RepoFile "sdk/$f") -NoNewline -Encoding UTF8
    }

    # NeurD_version.h is generated by media_sdk's CMake from NeurD_version.h.in
    # and the top-level project(... VERSION "x.y.z"). Reproduce that exactly.
    $top = Get-RepoFile 'CMakeLists.txt'
    $m = [regex]::Match($top, 'project\s*\(\s*mediasdk[^)]*VERSION\s+"?(\d+)\.(\d+)\.(\d+)"?')
    if (-not $m.Success) { throw "could not find project(mediasdk ... VERSION x.y.z) in CMakeLists.txt@$Ref" }
    $ver = (Get-RepoFile 'sdk/NeurD_version.h.in').
        Replace('@PROJECT_VERSION_MAJOR@', $m.Groups[1].Value).
        Replace('@PROJECT_VERSION_MINOR@', $m.Groups[2].Value).
        Replace('@PROJECT_VERSION_PATCH@', $m.Groups[3].Value)
    Set-Content -Path (Join-Path $inc 'NeurD_version.h') -Value $ver -NoNewline -Encoding UTF8

    Write-Host "NeurD headers $($m.Groups[1].Value).$($m.Groups[2].Value).$($m.Groups[3].Value) ($Repo@$Ref) -> $inc"
    exit 0
} catch {
    Write-Host "WARNING: NeurD header fetch failed: $_"
    Write-Host "         2D->3D lift will be compiled OUT (plug-in otherwise unchanged)."
    Write-Host "         Needs gh auth with read access to $Repo (gh auth login / GH_TOKEN)."
    # Do not leave a half-populated include dir that CMake would accept.
    if (Test-Path $inc) { Remove-Item -Recurse -Force $inc }
    exit 1
}
